[project]
name = "dafeng-server"
version = "0.1.0"
description = "Da feng server to help us code easy and happy"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.3",
    "sqlmodel>=0.0.22",
    "alembic>=1.13.3",
]
