"""add_db_table

Revision ID: 1516825cee75
Revises: 2559416cf4d3
Create Date: 2024-11-11 21:56:17.136881

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '1516825cee75'
down_revision = '2559416cf4d3'
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_table',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('db_type', sa.String(length=16), nullable=True, comment='数据库类型'),
    sa.Column('db_name', sa.String(length=32), nullable=True, comment='数据库名称'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='字段名称'),
    sa.Column('type', sa.String(length=32), nullable=True, comment='类型'),
    sa.Column('length', sa.Integer(), nullable=True, comment='长度'),
    sa.Column('decimals', sa.Integer(), nullable=True, comment='小数位数'),
    sa.Column('not_null', sa.Boolean(), nullable=True, comment='允许为空(0:允许, 1:不允许)'),
    sa.Column('key', sa.Boolean(), nullable=True, comment='是否主键(0:否, 1:是)'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.BigInteger(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.BigInteger(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='数据库表结构信息'
    )
    op.create_index('idx_db_name_type', 'sys_table', ['db_type', 'db_name'], unique=False)
    op.create_index(op.f('ix_sys_table_db_name'), 'sys_table', ['db_name'], unique=False)
    op.create_index(op.f('ix_sys_table_id'), 'sys_table', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_table_id'), table_name='sys_table')
    op.drop_index(op.f('ix_sys_table_db_name'), table_name='sys_table')
    op.drop_index('idx_db_name_type', table_name='sys_table')
    op.drop_table('sys_table')
    # ### end Alembic commands ###
