"""empty message

Revision ID: 547d049b6a63
Revises: 57b76db53e2a
Create Date: 2024-12-28 21:11:50.446904

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '547d049b6a63'
down_revision = '57b76db53e2a'
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('read_new_word',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户ID'),
    sa.Column('article_id', sa.BigInteger(), nullable=True, comment='文章ID'),
    sa.Column('word_id', sa.BigInteger(), nullable=True, comment='词库表ID'),
    sa.Column('word', sa.String(length=32), nullable=True, comment='单词'),
    sa.Column('review_count', sa.Integer(), nullable=True, comment='复习次数'),
    sa.Column('next_review_date', sa.DateTime(), nullable=True, comment='复习时间'),
    sa.Column('tenant_id', sa.Integer(), nullable=True, comment='租户ID'),
    sa.Column('create_time', sa.BigInteger(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.BigInteger(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='阅读生词表'
    )
    op.create_index('idx_my_tenantId_userId_word', 'read_new_word', ['tenant_id', 'user_id', 'word'], unique=False)
    op.create_index('idx_nd_tenantId_userid_articleId', 'read_new_word', ['tenant_id', 'user_id', 'article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_nd_tenantId_userid_articleId', table_name='read_new_word')
    op.drop_index('idx_my_tenantId_userId_word', table_name='read_new_word')
    op.drop_table('read_new_word')
    # ### end Alembic commands ###
