"""empty message

Revision ID: fe0d0b29dd75
Revises: 29fee01fb305
Create Date: 2024-12-14 20:09:30.478490

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe0d0b29dd75'
down_revision = '29fee01fb305'
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_database', sa.Column('owner', sa.String(length=64), nullable=True, comment='拥有者'))
    op.add_column('db_database', sa.Column('template', sa.String(length=64), nullable=True, comment='使用模板'))
    op.add_column('db_database', sa.Column('encoding', sa.String(length=32), nullable=True, comment='字符编码'))
    op.add_column('db_database', sa.Column('collation_order', sa.String(length=32), nullable=True, comment='排序规则'))
    op.add_column('db_database', sa.Column('character_classification', sa.String(length=32), nullable=True, comment='字符分类'))
    op.add_column('db_database', sa.Column('tablespace', sa.String(length=64), nullable=True, comment='表空间名称'))
    op.add_column('db_database', sa.Column('connection_limit', sa.Integer(), nullable=True, comment='连接限制'))
    op.add_column('db_database', sa.Column('allow_connection', sa.Boolean(), nullable=True, comment='是否允许连接'))
    op.add_column('db_database', sa.Column('is_template', sa.Boolean(), nullable=True, comment='是否为模板数据库'))
    op.alter_column('db_database', 'database_name',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='数据库名称',
               existing_nullable=False)
    op.drop_column('db_database', 'character_set')
    op.drop_column('db_database', 'collation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_database', sa.Column('collation', mysql.VARCHAR(length=32), nullable=True, comment='排序规则'))
    op.add_column('db_database', sa.Column('character_set', mysql.VARCHAR(length=32), nullable=True, comment='字符编码'))
    op.alter_column('db_database', 'database_name',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=32),
               existing_comment='数据库名称',
               existing_nullable=False)
    op.drop_column('db_database', 'is_template')
    op.drop_column('db_database', 'allow_connection')
    op.drop_column('db_database', 'connection_limit')
    op.drop_column('db_database', 'tablespace')
    op.drop_column('db_database', 'character_classification')
    op.drop_column('db_database', 'collation_order')
    op.drop_column('db_database', 'encoding')
    op.drop_column('db_database', 'template')
    op.drop_column('db_database', 'owner')
    # ### end Alembic commands ###
