"""empty message

Revision ID: 3cc02b716ca0
Revises: 05014077cea8
Create Date: 2024-12-14 17:11:21.496846

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cc02b716ca0'
down_revision = '05014077cea8'
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_connection', sa.Column('connection_database', sa.String(length=64), nullable=True, comment='连接数据库名称'))
    op.drop_column('db_connection', 'database_ext')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_connection', sa.Column('database_ext', mysql.VARCHAR(length=64), nullable=True, comment='数据库扩展信息'))
    op.drop_column('db_connection', 'connection_database')
    # ### end Alembic commands ###
