"""empty message

Revision ID: 29fee01fb305
Revises: 3cc02b716ca0
Create Date: 2024-12-14 18:13:09.619483

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29fee01fb305'
down_revision = '3cc02b716ca0'
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('db_field', 'default',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='默认值',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('db_field', 'default',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=32),
               existing_comment='默认值',
               existing_nullable=True)
    # ### end Alembic commands ###
