"""empty message

Revision ID: 7bcb67b1c853
Revises: fe0d0b29dd75
Create Date: 2024-12-14 20:35:18.002748

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '7bcb67b1c853'
down_revision = 'fe0d0b29dd75'
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
