"""init_tables

Revision ID: 71674e8cc4dd
Revises: 
Create Date: 2024-11-13 21:39:20.840342

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '71674e8cc4dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_connection',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('connection_name', sa.String(length=32), nullable=True, comment='连接名称'),
    sa.Column('database_type', sa.String(length=16), nullable=True, comment='数据库类型'),
    sa.Column('server_version', sa.String(length=16), nullable=True, comment='数据库版本'),
    sa.Column('host', sa.String(length=16), nullable=True, comment='主机'),
    sa.Column('port', sa.Integer(), nullable=True, comment='端口号'),
    sa.Column('username', sa.String(length=32), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=63), nullable=True, comment='密码'),
    sa.Column('sessions', sa.Integer(), nullable=True, comment='活跃连接数'),
    sa.Column('client_character_set', sa.String(length=16), nullable=True, comment='客户端编码'),
    sa.Column('create_time', sa.BigInteger(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.BigInteger(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='连接信息表'
    )
    op.create_index(op.f('ix_sys_connection_connection_name'), 'sys_connection', ['connection_name'], unique=False)
    op.create_index(op.f('ix_sys_connection_id'), 'sys_connection', ['id'], unique=True)
    op.create_table('sys_database',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('connection_id', sa.BigInteger(), nullable=True, comment='连接id'),
    sa.Column('database_name', sa.String(length=32), nullable=True, comment='数据库名称'),
    sa.Column('character_set', sa.String(length=32), nullable=True, comment='字符编码'),
    sa.Column('collation', sa.String(length=32), nullable=True, comment='排序规则'),
    sa.Column('create_time', sa.BigInteger(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.BigInteger(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='数据库信息表'
    )
    op.create_index(op.f('ix_sys_database_database_name'), 'sys_database', ['database_name'], unique=False)
    op.create_index(op.f('ix_sys_database_id'), 'sys_database', ['id'], unique=True)
    op.create_table('sys_field',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('table_id', sa.BigInteger(), nullable=True, comment='表id'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='字段名称'),
    sa.Column('type', sa.String(length=32), nullable=True, comment='类型'),
    sa.Column('length', sa.Integer(), nullable=True, comment='长度'),
    sa.Column('decimals', sa.Integer(), nullable=True, comment='小数位数'),
    sa.Column('not_null', sa.Boolean(), nullable=True, comment='允许为空(0:允许, 1:不允许)'),
    sa.Column('key', sa.Boolean(), nullable=True, comment='是否主键(0:否, 1:是)'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.BigInteger(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.BigInteger(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='表字段信息表'
    )
    op.create_index(op.f('ix_sys_field_id'), 'sys_field', ['id'], unique=True)
    op.create_table('sys_index',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('table_id', sa.BigInteger(), nullable=True, comment='表id'),
    sa.Column('name', sa.String(length=32), nullable=True, comment='索引名称'),
    sa.Column('field', sa.String(length=63), nullable=True, comment='索引字段'),
    sa.Column('type', sa.String(length=16), nullable=True, comment='索引类型'),
    sa.Column('method', sa.String(length=16), nullable=True, comment='索引方法'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.BigInteger(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.BigInteger(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='索引信息表'
    )
    op.create_index(op.f('ix_sys_index_id'), 'sys_index', ['id'], unique=True)
    op.create_table('sys_table',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('database_id', sa.BigInteger(), nullable=True, comment='数据库id'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='表名称'),
    sa.Column('rows', sa.Integer(), nullable=True, comment='行数'),
    sa.Column('index_length', sa.String(length=32), nullable=True, comment='索引长度'),
    sa.Column('data_length', sa.String(length=32), nullable=True, comment='数据长度'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.BigInteger(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.BigInteger(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='表结构信息'
    )
    op.create_index(op.f('ix_sys_table_id'), 'sys_table', ['id'], unique=True)
    op.create_table('sys_user',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('username', sa.String(length=32), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=64), nullable=True, comment='密码'),
    sa.Column('nickname', sa.String(length=32), nullable=True, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=64), nullable=True, comment='头像地址'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态(0:停用,1:待审核,2:正常,3:已注销)'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.BigInteger(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.BigInteger(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户信息表'
    )
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=True)
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_table_id'), table_name='sys_table')
    op.drop_table('sys_table')
    op.drop_index(op.f('ix_sys_index_id'), table_name='sys_index')
    op.drop_table('sys_index')
    op.drop_index(op.f('ix_sys_field_id'), table_name='sys_field')
    op.drop_table('sys_field')
    op.drop_index(op.f('ix_sys_database_id'), table_name='sys_database')
    op.drop_index(op.f('ix_sys_database_database_name'), table_name='sys_database')
    op.drop_table('sys_database')
    op.drop_index(op.f('ix_sys_connection_id'), table_name='sys_connection')
    op.drop_index(op.f('ix_sys_connection_connection_name'), table_name='sys_connection')
    op.drop_table('sys_connection')
    # ### end Alembic commands ###
