server:
  name: Da feng
  host: 0.0.0.0
  port: 19001
  version: 0.1.0
  app_desc: Da feng helps us work more easily and happily
  api_version: /v1
  workers: 8

database:
  dialog: sqlite
  # When use sqlite do not need to set url and default in src/main/resource/alembic/db/server.db
  # Url format: driver://user:pass@localhost:port/dbname
  url: ""
  pool_recycle: 20
  echo_sql: True
